"""
Django settings for chatbot_project project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-&%5en3qok*cvwlvjt42l0$9d-0((e6f)p(lc&ll8o=+uuagyk1'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Our custom app that houses the ChatterBot terminal client
    'chatbot',
]

# ---------------------------------------------------------------------------
# ChatterBot configuration
# ---------------------------------------------------------------------------
# ChatterBot needs to know:
#   1) What name to give the bot
#   2) Which storage adapter to use to persist learned conversations
#      (SQLStorageAdapter lets it reuse Django's own SQLite database file)
#   3) Which logic adapters decide how a response is chosen
# Keeping this configuration in settings.py (instead of hard-coding it in the
# management command) means any other part of the Django project could reuse
# the same bot configuration later (e.g. a future web view).
CHATTERBOT = {
    'name': 'DjangoBot',
    'storage_adapter': 'chatterbot.storage.SQLStorageAdapter',
    'database_uri': 'sqlite:///' + str(BASE_DIR / 'db.sqlite3'),
    'logic_adapters': [
        'chatterbot.logic.BestMatch',
    ],
    # ChatterBot's default tagger (PosLemmaTagger) needs the "en_core_web_sm"
    # spaCy model to be downloaded separately (`python -m spacy download
    # en_core_web_sm`). LowercaseTagger uses spaCy's built-in blank English
    # tokenizer instead, so it works out-of-the-box with no extra downloads,
    # which keeps setup simple for this assignment. (Resolved to an actual
    # class in chat.py, since ChatterBot expects a class object here rather
    # than a dotted import string.)
    'tagger': 'chatterbot.tagging.LowercaseTagger',
    # Language corpus used when training with --train
    'training_corpus': 'chatterbot.corpus.english',
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'chatbot_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'chatbot_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
